### ISSUE TITLE
Movie.vue loadCityList error

### ISSUE THREAD

**Issue by jiangxiaoxin** [JasonBai007/suanban#1]
在Movie.vue的loadCityList这个方法里使用 vue-resource 里的jsonp方法去获取数据，我run dev之后发现报了一个错误，`Error in mounted hook: "TypeError: Cannot read property 'jsonp' of undefined。`只要把main.js里的`require('vue-resource')`那一行换成 `import vueResource from 'vue-resource'; `这种写法就好。刚学习前端，不知这是什么问题？

**Comment by JasonBai007** [comment]
以前我也遇到过这种情况，感觉是因为vue-cli规定只能用import，因为使用vue-cli创建一个空项目后，你会发现main.js里开头两行的注释：// The Vue build version to load with the `import` command
说明官方在生成的文件中注释说明了要用Import。
